#-------------------------------------------------
#
# Project created by QtCreator 2019-07-30T21:56:39
#
#-------------------------------------------------

QT += core gui widgets xml


RC_ICONS = icon.ico
TARGET = Tanki
TEMPLATE = app

DESTDIR = build
OBJECTS_DIR = objects
MOC_DIR = moc
UI_DIR = ui
RCC_DIR = res

INCLUDEPATH  = $${PROJECT_ROOT_PATH}../../MyList/

DEFINES += QT_DEPRECATED_WARNINGS


CONFIG += c++17


win32: {
    INCLUDEPATH += C:/VulkanSDK/1.4.321.1/Include
}

linux: {
    QMAKE_LFLAGS_RELEASE += -Wl,--strip-all

    LIBS += -lX11
    LIBS += -lxcb
}


FORMS += \
    mainwindow.ui

HEADERS += \
    Canvas.h \
    Debug.h \
    hardware/alternativa/engine3d/core/Faces.h \
    hardware/alternativa/engine3d/materials/DrawParams.h \
    Error.h \
    FPSService.h \
    Graphics.h \
    Material_isType.h \
    MyList/MyList.h \
    MyMath.h \
    Object3D_isType.h \
    ResourcesData.h \
    _global.h \
    _init.h \
    entrance/alternativa/tanks/service/settings/keybinding/GameActionEnum.h \
    entrance/alternativa/types/Long.h \
    entrance/alternativa/types/LongHash.h \
    entrance/platform/client/fp10/core/model/IModel.h \
    entrance/platform/client/fp10/core/model/impl/Model.h \
    entrance/platform/client/fp10/core/registry/ResourceRegistry.h \
    entrance/platform/client/fp10/core/registry/impl/ResourceRegistryImpl.h \
    entrance/platform/client/fp10/core/resource/Resource.h \
    entrance/platform/client/fp10/core/resource/ResourceInfo.h \
    entrance/platform/client/fp10/core/resource/tara/TARAParser.h \
    entrance/platform/client/fp10/core/resource/types/MultiframeTextureResource.h \
    entrance/platform/client/fp10/core/resource/types/StubBitmapData.h \
    entrance/platform/client/fp10/core/resource/types/TextureResource.h \
    entrance/platform/client/fp10/core/type/GameObjectValue.h \
    entrance/platform/client/fp10/core/type/IGameObject.h \
    entrance/platform/client/fp10/core/type/IGameObjectInternal.h \
    entrance/platform/client/fp10/core/type/ISpace.h \
    entrance/platform/client/fp10/core/type/impl/GameObject.h \
    entrance/platform/client/fp10/core/type/impl/Space.h \
    entrance/platform/core/general/resource/types/imageframe/ResourceImageFrameParams.h \
    entrance/projects/tanks/client/battleservice/model/battle/team/BattleTeam.h \
    entrance/projects/tanks/clients/flash/commons/models/coloring/IColoring.h \
    file.h \
    flash/display/BitmapData.h \
    flash/display/BlendMode.h \
    flash/display/BlendMode.h \
    flash/display/BlendMode.h \
    flash/display/IBitmapDrawable.h \
    flash/display/IBitmapDrawable.h \
    flash/display3D/VK_IndexBuffer3D.h \
    flash/display3D/VK_VertexBuffer3D.h \
    flash/geom/ColorTransform.h \
    flash/geom/GeomRectangle.h \
    flash/geom/Matrix.h \
    flash/geom/Matrix3D.h \
    flash/geom/Point.h \
    flash/geom/Vector3D.h \
    game/alternativa/math/Matrix3.h \
    game/alternativa/math/Matrix4.h \
    game/alternativa/math/Quaternion.h \
    game/alternativa/math/Vector3.h \
    game/alternativa/physics/Body.h \
    game/alternativa/physics/BodyContact.h \
    game/alternativa/physics/BodyState.h \
    game/alternativa/physics/PhysicsMaterial.h \
    game/alternativa/physics/PhysicsScene.h \
    game/alternativa/physics/PhysicsUtils.h \
    game/alternativa/physics/QuickUnionFind.h \
    game/alternativa/physics/ShapeContact.h \
    game/alternativa/physics/collision/BodyCollisionFilter.h \
    game/alternativa/physics/collision/Collider.h \
    game/alternativa/physics/collision/CollisionDetector.h \
    game/alternativa/physics/collision/CollisionKdNode.h \
    game/alternativa/physics/collision/CollisionKdTree.h \
    game/alternativa/physics/collision/CollisionKdTree2D.h \
    game/alternativa/physics/collision/CollisionShape.h \
    game/alternativa/physics/collision/IRayCollisionFilter.h \
    game/alternativa/physics/collision/colliders/BoxBoxCollider.h \
    game/alternativa/physics/collision/colliders/BoxRectCollider.h \
    game/alternativa/physics/collision/colliders/BoxSphereCollider.h \
    game/alternativa/physics/collision/colliders/BoxTriangleCollider.h \
    game/alternativa/physics/collision/colliders/ColliderUtils.h \
    game/alternativa/physics/collision/colliders/CollidersVertex.h \
    game/alternativa/physics/collision/colliders/FaceSide.h \
    game/alternativa/physics/collision/colliders/PolygonsIntersectionUtils.h \
    game/alternativa/physics/collision/primitives/CollisionBox.h \
    game/alternativa/physics/collision/primitives/CollisionRect.h \
    game/alternativa/physics/collision/primitives/CollisionSphere.h \
    game/alternativa/physics/collision/primitives/CollisionTriangle.h \
    game/alternativa/physics/collision/types/AABB.h \
    game/alternativa/physics/collision/types/RayHit.h \
    game/alternativa/physics/contactislands/ContactIsland.h \
    game/alternativa/physics/contactislands/ContactLevels.h \
    game/alternativa/physics/contactislands/IslandsGenerator.h \
    game/alternativa/proplib/PropLibRegistry.h \
    game/alternativa/proplib/PropLibrary.h \
    game/alternativa/proplib/objects/PropMesh.h \
    game/alternativa/proplib/objects/PropObject.h \
    game/alternativa/proplib/objects/PropObjectType.h \
    game/alternativa/proplib/objects/PropSprite.h \
    game/alternativa/proplib/types/PropData.h \
    game/alternativa/proplib/types/PropGroup.h \
    game/alternativa/proplib/types/PropLOD.h \
    game/alternativa/proplib/types/PropState.h \
    game/alternativa/proplib/utils/ByteArrayMap.h \
    game/alternativa/proplib/utils/TextureByteDataMap.h \
    game/alternativa/tanks/battle/DeferredAction.h \
    game/alternativa/tanks/battle/objects/tank/tankskin/SkinMaterials.h \
    game/alternativa/tanks/battle/objects/tank/tankskin/TrackSkin.h \
    game/alternativa/tanks/battle/objects/tank/tankskin/TracksAnimator.h \
    game/alternativa/tanks/battle/objects/tank/tankskin/materialfactory/DefaultTankSkinMaterialsFactory.h \
    game/alternativa/tanks/battle/objects/tank/tankskin/materialfactory/TankSkinMaterialsFactory.h \
    game/alternativa/tanks/battle/scene3d/DecalFactory.h \
    game/alternativa/tanks/battle/scene3d/DeferredRendererAddition.h \
    game/alternativa/tanks/battle/scene3d/DeferredRendererDeletion.h \
    game/alternativa/tanks/battle/scene3d/RenderGroup.h \
    game/alternativa/tanks/battle/scene3d/Renderer.h \
    game/alternativa/tanks/battle/scene3d/RotationState.h \
    game/alternativa/tanks/battle/scene3d/scene3dcontainer/Scene3DContainer.h \
    game/alternativa/tanks/battle/utils/AddPostPhysicsControllerAction.h \
    game/alternativa/tanks/battle/utils/PhysicsControllerDeferredAction.h \
    game/alternativa/tanks/battle/utils/RemovePostPhysicsController.h \
    game/alternativa/tanks/engine3d/AnimatedSprite3D.h \
    game/alternativa/tanks/engine3d/CachedEntityStat.h \
    game/alternativa/tanks/engine3d/DefaultEffectsMaterialRegistry.h \
    game/alternativa/tanks/engine3d/DefaultTextureMaterialFactory.h \
    game/alternativa/tanks/engine3d/EffectsMaterialRegistry.h \
    game/alternativa/tanks/engine3d/MaterialEntry.h \
    game/alternativa/tanks/engine3d/MutableTextureMaterialRegistry.h \
    game/alternativa/tanks/engine3d/MutableTextureRegistry.h \
    game/alternativa/tanks/engine3d/TextureAnimation.h \
    game/alternativa/tanks/engine3d/TextureMaterialFactory.h \
    game/alternativa/tanks/engine3d/TextureMaterialRegistryBase.h \
    game/alternativa/tanks/engine3d/UVFrame.h \
    game/alternativa/tanks/model/item3d/Object3DSModel.h \
    game/alternativa/tanks/models/battle/battlefield/map/Billboards.h \
    game/alternativa/tanks/models/battle/battlefield/map/NormalsCalculator.h \
    game/alternativa/tanks/models/battle/battlefield/map/TexturedSpritesCollection.h \
    game/alternativa/tanks/models/tank/ITankModelAdapt.h \
    game/alternativa/tanks/models/tank/InitTankPartAdapt.h \
    game/alternativa/tanks/models/tank/WeaponMountProviderAdapt.h \
    game/alternativa/tanks/models/tank/configuration/TankConfigurationAdapt.h \
    game/alternativa/tanks/models/tank/configuration/TankConfigurationModel.h \
    game/alternativa/tanks/models/tank/hullcommon/HullCommonAdapt.h \
    game/alternativa/tanks/models/tank/hullcommon/HullCommonModel.h \
    game/alternativa/tanks/models/tank/speedcharacteristics/SpeedCharacteristicsAdapt.h \
    game/alternativa/tanks/models/weapon/IWeaponModelAdapt.h \
    game/alternativa/tanks/models/weapon/angles/verticals/autoaiming/VerticalAutoAimingAdapt.h \
    game/alternativa/tanks/models/weapon/angles/verticals/verticalangles/VerticalAngles.h \
    game/alternativa/tanks/models/weapon/angles/verticals/verticalangles/VerticalAnglesAdapt.h \
    game/alternativa/tanks/models/weapon/angles/verticals/verticalangles/WeaponVerticalAnglesModel.h \
    game/alternativa/tanks/models/weapon/angles/verticals/autoaiming/VerticalAutoAimingModel.h \
    game/alternativa/tanks/models/weapon/common/WeaponCommonModel.h \
    game/alternativa/tanks/models/weapon/common/asWeaponCommon.h \
    game/alternativa/tanks/models/weapon/shared/shot/DiscreteShotModel.h \
    game/alternativa/tanks/models/weapon/shared/shot/IShotModelAdapt.h \
    game/alternativa/tanks/models/weapon/splash/Splash.h \
    game/alternativa/tanks/models/weapon/turret/IRotatingTurretModel.h \
    game/alternativa/tanks/models/weapon/turret/IRotatingTurretModelAdapt.h \
    game/alternativa/tanks/models/weapon/twins/ITwinsSFXModel.h \
    game/alternativa/tanks/models/weapon/twins/ITwinsSFXModelAdapt.h \
    game/alternativa/tanks/models/weapon/twins/RemoteTwinsWeapon.h \
    game/alternativa/tanks/models/weapon/twins/TwinsAmmunition.h \
    game/alternativa/tanks/models/weapon/twins/TwinsEffects.h \
    game/alternativa/tanks/models/weapon/twins/TwinsModel.h \
    game/alternativa/tanks/models/weapon/twins/TwinsSFXData.h \
    game/alternativa/tanks/models/weapon/twins/TwinsSFXModel.h \
    game/alternativa/tanks/models/weapon/twins/TwinsShot.h \
    game/alternativa/tanks/models/weapon/twins/TwinsShotParams.h \
    game/alternativa/tanks/models/weapon/twins/TwinsWeapon.h \
    game/alternativa/tanks/models/weapon/twins/TwinsWeaponCallback.h \
    game/alternativa/tanks/models/weapon/twins/TwinsWeaponCallbackAdapt.h \
    game/alternativa/tanks/models/weapon/weakening/IWeaponWeakeningModelAdapt.h \
    game/alternativa/tanks/models/weapon/weakening/WeaponWeakeningData.h \
    game/alternativa/tanks/models/weapon/weakening/WeaponWeakeningModel.h \
    game/alternativa/tanks/models/weapons/shell/InelasticShell.h \
    game/alternativa/tanks/models/weapons/shell/Shell.h \
    game/alternativa/tanks/models/weapons/shell/states/DummyShellStates.h \
    game/alternativa/tanks/models/weapons/shell/states/ShellStates.h \
    game/alternativa/tanks/sfx/AnimatedSpriteEffect.h \
    game/alternativa/tanks/sfx/DecalEffect.h \
    game/alternativa/tanks/sfx/GraphicEffect.h \
    game/alternativa/tanks/sfx/Object3DPositionProvider.h \
    game/alternativa/tanks/sfx/PlaneMuzzleFlashEffect.h \
    game/alternativa/tanks/sfx/SFXUtils.h \
    game/alternativa/tanks/sfx/SimplePlane.h \
    game/alternativa/tanks/sfx/StaticObject3DPositionProvider.h \
    game/alternativa/tanks/sfx/christmas/ChristmasTreeToyEffect.h \
    game/alternativa/tanks/battle/BattleRunner.h \
    game/alternativa/tanks/battle/BattleService.h \
    game/alternativa/tanks/battle/BattleUtils.h \
    game/alternativa/tanks/battle/BattleView.h \
    game/alternativa/tanks/battle/LogicUnit.h \
    game/alternativa/tanks/battle/PerformanceMonitor.h \
    game/alternativa/tanks/battle/PhysicsController.h \
    game/alternativa/tanks/battle/PhysicsInterpolator.h \
    game/alternativa/tanks/battle/PostPhysicsController.h \
    game/alternativa/tanks/battle/objects/tank/ClientTankState.h \
    game/alternativa/tanks/battle/objects/tank/CollisionBoxesBuilder.h \
    game/alternativa/tanks/battle/objects/tank/EncryptedValueSmoother.h \
    game/alternativa/tanks/battle/objects/tank/HullNotFoundError.h \
    game/alternativa/tanks/battle/objects/tank/HullTransformUpdater.h \
    game/alternativa/tanks/battle/objects/tank/LocalHullTransformUpdater.h \
    game/alternativa/tanks/battle/objects/tank/LocalWeapon.h \
    game/alternativa/tanks/battle/objects/tank/RemoteHullTransformUpdater.h \
    game/alternativa/tanks/battle/objects/tank/SimpleValueSmoother.h \
    game/alternativa/tanks/battle/objects/tank/Tank.h \
    game/alternativa/tanks/battle/objects/tank/TankConst.h \
    game/alternativa/tanks/battle/objects/tank/TankControlLockBits.h \
    game/alternativa/tanks/battle/objects/tank/TurretMountPointNotFoundError.h \
    game/alternativa/tanks/battle/objects/tank/ValueSmoother.h \
    game/alternativa/tanks/battle/objects/tank/Weapon.h \
    game/alternativa/tanks/battle/objects/tank/WeaponMount.h \
    game/alternativa/tanks/battle/objects/tank/WeaponPlatform.h \
    game/alternativa/tanks/battle/objects/tank/controllers/BarrelElevator.h \
    game/alternativa/tanks/battle/objects/tank/controllers/ChassisControlListener.h \
    game/alternativa/tanks/battle/objects/tank/controllers/ChassisController.h \
    game/alternativa/tanks/battle/objects/tank/controllers/LocalChassisController.h \
    game/alternativa/tanks/battle/objects/tank/controllers/LocalTurretController.h \
    game/alternativa/tanks/battle/objects/tank/controllers/Turret.h \
    game/alternativa/tanks/battle/objects/tank/tankchassis/SuspensionParams.h \
    game/alternativa/tanks/battle/objects/tank/tankchassis/SuspensionRay.h \
    game/alternativa/tanks/battle/objects/tank/tankchassis/Track.h \
    game/alternativa/tanks/battle/objects/tank/tankchassis/TrackedChassis.h \
    game/alternativa/tanks/battle/objects/tank/tankskin/TankHullSkinCacheItem.h \
    game/alternativa/tanks/battle/objects/tank/tankskin/TankSkin.h \
    game/alternativa/tanks/battle/objects/tank/tankskin/TankSkinPartCacheItem.h \
    game/alternativa/tanks/battle/objects/tank/tankskin/turret/CustomTurretSkin.h \
    game/alternativa/tanks/battle/objects/tank/tankskin/turret/TurretGeometryItem.h \
    game/alternativa/tanks/battle/objects/tank/tankskin/turret/TurretSkin.h \
    game/alternativa/tanks/battle/objects/tank/tankskin/turret/TurretSkinCacheItem.h \
    game/alternativa/tanks/battle/scene3d/AmbientShadows.h \
    game/alternativa/tanks/battle/scene3d/BattleScene3D.h \
    game/alternativa/tanks/battle/scene3d/Object3DNames.h \
    game/alternativa/tanks/battle/scene3d/scene3dcontainer/Object3DContainerProxy.h \
    game/alternativa/tanks/battle/utils/DampedSpring.h \
    game/alternativa/tanks/camera/CameraController.h \
    game/alternativa/tanks/camera/CameraPositionData.h \
    game/alternativa/tanks/camera/CameraTarget.h \
    game/alternativa/tanks/camera/DummyCameraController.h \
    game/alternativa/tanks/camera/FollowCameraController.h \
    game/alternativa/tanks/camera/GameCamera.h \
    game/alternativa/tanks/display/AxisIndicator.h \
    game/alternativa/tanks/engine3d/IndexedTextureConstructor.h \
    game/alternativa/tanks/models/battle/battlefield/BattlefieldModel.h \
    game/alternativa/tanks/models/battle/battlefield/CommonTargetEvaluatorConst.h \
    game/alternativa/tanks/models/battle/battlefield/map/CollisionGeometryParser.h \
    game/alternativa/tanks/models/battle/battlefield/map/CollisionGeometryToXml.h \
    game/alternativa/tanks/models/battle/battlefield/map/HelperMesh.h \
    game/alternativa/tanks/models/battle/battlefield/map/MapBuilder.h \
    game/alternativa/tanks/models/battle/battlefield/map/MapGeometryParser.h \
    game/alternativa/tanks/models/battle/battlefield/map/MapTexturesBuilder.h \
    game/alternativa/tanks/models/battle/battlefield/map/TexturedBSPsCollection.h \
    game/alternativa/tanks/models/battle/battlefield/map/TexturedMeshesCollection.h \
    game/alternativa/tanks/models/battle/battlefield/map/TexturedPropsCollection.h \
    game/alternativa/tanks/models/battle/battlefield/map/TexturedPropsRegistry.h \
    game/alternativa/tanks/models/map/BattleMapModel.h \
    game/alternativa/tanks/models/map/IBattleMap.h \
    game/alternativa/tanks/models/tank/HullsRegistry.h \
    game/alternativa/tanks/models/tank/ITankModel.h \
    game/alternativa/tanks/models/tank/IWeaponController.h \
    game/alternativa/tanks/models/tank/InitTankPart.h \
    game/alternativa/tanks/models/tank/LocalTankInfoService.h \
    game/alternativa/tanks/models/tank/LocalWeaponController.h \
    game/alternativa/tanks/models/tank/RemoteWeaponController.h \
    game/alternativa/tanks/models/tank/TankModel.h \
    game/alternativa/tanks/models/tank/TankPartsRegistry.h \
    game/alternativa/tanks/models/tank/TurretsRegistry.h \
    game/alternativa/tanks/models/tank/WeaponMountProvider.h \
    game/alternativa/tanks/models/tank/configuration/TankConfiguration.h \
    game/alternativa/tanks/models/tank/hullcommon/HullCommon.h \
    game/alternativa/tanks/models/tank/speedcharacteristics/SpeedCharacteristics.h \
    game/alternativa/tanks/models/tank/speedcharacteristics/SpeedCharacteristicsModel.h \
    game/alternativa/tanks/models/weapon/AllGlobalGunParams.h \
    game/alternativa/tanks/models/weapon/IWeaponModel.h \
    game/alternativa/tanks/models/weapon/RayCollisionFilter.h \
    game/alternativa/tanks/models/weapon/WeaponConst.h \
    game/alternativa/tanks/models/weapon/WeaponForces.h \
    game/alternativa/tanks/models/weapon/WeaponObject.h \
    game/alternativa/tanks/models/weapon/WeaponUtils.h \
    game/alternativa/tanks/models/weapon/angles/verticals/autoaiming/VerticalAutoAiming.h \
    game/alternativa/tanks/models/weapon/artillery/rotation/ArtilleryElevatingBarrelModel.h \
    game/alternativa/tanks/models/weapon/artillery/rotation/BarrelElevationController.h \
    game/alternativa/tanks/models/weapon/common/HitInfo.h \
    game/alternativa/tanks/models/weapon/common/IWeaponCommonModel.h \
    game/alternativa/tanks/models/weapon/common/IWeaponCommonModelAdapt.h \
    game/alternativa/tanks/models/weapon/common/WeaponCommonData.h \
    game/alternativa/tanks/models/weapon/shared/CommonTargetEvaluator.h \
    game/alternativa/tanks/models/weapon/shared/MarginalCollider.h \
    game/alternativa/tanks/models/weapon/shared/SimpleWeaponController.h \
    game/alternativa/tanks/models/weapon/shared/shot/IShotModel.h \
    game/alternativa/tanks/models/weapon/smoky/RemoteSmokyWeapon.h \
    game/alternativa/tanks/models/weapon/smoky/SmokyWeapon.h \
    game/alternativa/tanks/models/weapon/turret/RotatingTurretModel.h \
    game/alternativa/tanks/models/weapon/weakening/DistanceWeakening.h \
    game/alternativa/tanks/models/weapon/weakening/IWeaponWeakeningModel.h \
    game/alternativa/tanks/models/weapons/targeting/CommonTargetingSystem.h \
    game/alternativa/tanks/models/weapons/targeting/TargetingResult.h \
    game/alternativa/tanks/models/weapons/targeting/TargetingSystem.h \
    game/alternativa/tanks/models/weapons/targeting/direction/TargetingDirection.h \
    game/alternativa/tanks/models/weapons/targeting/direction/TargetingDirectionCalculator.h \
    game/alternativa/tanks/models/weapons/targeting/direction/sector/SectorDirectionCalculator.h \
    game/alternativa/tanks/models/weapons/targeting/direction/sector/TargetingSector.h \
    game/alternativa/tanks/models/weapons/targeting/direction/sector/TargetingSectorList.h \
    game/alternativa/tanks/models/weapons/targeting/direction/sector/TargetingSectorsCalculator.h \
    game/alternativa/tanks/models/weapons/targeting/direction/sector/splitter/SectorsSplitter.h \
    game/alternativa/tanks/models/weapons/targeting/direction/sector/splitter/SortedTargetingSectors.h \
    game/alternativa/tanks/models/weapons/targeting/priority/TargetingPriorityCalculator.h \
    game/alternativa/tanks/models/weapons/targeting/priority/targeting/CommonTargetPriorityCalculator.h \
    game/alternativa/tanks/models/weapons/targeting/priority/targeting/TargetPriorityCalculator.h \
    game/alternativa/tanks/models/weapons/targeting/processor/CommonDirectionProcessor.h \
    game/alternativa/tanks/models/weapons/targeting/processor/SingleTargetDirectionProcessor.h \
    game/alternativa/tanks/models/weapons/targeting/processor/TargetingDirectionProcessor.h \
    game/alternativa/tanks/physics/CollisionGroup.h \
    game/alternativa/tanks/physics/MinMax.h \
    game/alternativa/tanks/physics/SoaringChecker.h \
    game/alternativa/tanks/physics/TankBody.h \
    game/alternativa/tanks/physics/TankBodyIdProvider.h \
    game/alternativa/tanks/physics/TankPhysicsScene.h \
    game/alternativa/tanks/physics/TanksCollisionDetector.h \
    game/alternativa/tanks/services/battleinput/BattleInputService.h \
    game/alternativa/tanks/services/battleinput/BattleInputServiceImpl.h \
    game/alternativa/tanks/services/battleinput/GameActionListener.h \
    game/alternativa/tanks/services/tankregistry/TankUsersRegistry.h \
    game/alternativa/tanks/services/tankregistry/TankUsersRegistryServiceImpl.h \
    game/alternativa/tanks/utils/BitMask.h \
    game/alternativa/tanks/utils/BitVector.h \
    game/alternativa/tanks/utils/ConstEncryptedNumber.h \
    game/alternativa/tanks/utils/EncryptedInt.h \
    game/alternativa/tanks/utils/EncryptedIntImpl.h \
    game/alternativa/tanks/utils/EncryptedNumber.h \
    game/alternativa/tanks/utils/EncryptedNumberImpl.h \
    game/alternativa/tanks/utils/GraphicsUtils.h \
    game/alternativa/tanks/utils/MathUtils.h \
    game/alternativa/tanks/utils/Vector3Validator.h \
    game/alternativa/tanks/utils/objectpool/ObjectPool.h \
    game/alternativa/tanks/utils/objectpool/Pool.h \
    game/alternativa/tanks/utils/objectpool/PooledObject.h \
    game/alternativa/utils/TextureMaterialRegistry.h \
    game/alternativa/utils/XMLUtils.h \
    game/alternativa/utils/textureutils/ITextureConstructorListener.h \
    game/alternativa/utils/textureutils/TextureByteData.h \
    game/alternativa/utils/textureutils/TextureConstructor.h \
    game/projects/tanks/client/battlefield/models/tankparts/armor/common/HullCommonCC.h \
    game/projects/tanks/client/battlefield/models/tankparts/armor/common/HullCommonModelBase.h \
    game/projects/tanks/client/battlefield/models/tankparts/sfx/shoot/twins/TwinsShootSFXCC.h \
    game/projects/tanks/client/battlefield/models/tankparts/sfx/shoot/twins/TwinsShootSFXModelBase.h \
    game/projects/tanks/client/battlefield/models/tankparts/weapon/angles/verticals/autoaiming/VerticalAutoAimingModelBase.h \
    game/projects/tanks/client/battlefield/models/tankparts/weapon/angles/verticals/verticalangles/WeaponVerticalAnglesModelBase.h \
    game/projects/tanks/client/battlefield/models/tankparts/weapon/angles/verticals/verticalangles/VerticalAnglesCC.h \
    game/projects/tanks/client/battlefield/models/tankparts/weapon/common/WeaponCommonCC.h \
    game/projects/tanks/client/battlefield/models/tankparts/weapon/common/WeaponCommonModelBase.h \
    game/projects/tanks/client/battlefield/models/tankparts/weapon/common/shell/ShellState.h \
    game/projects/tanks/client/battlefield/models/tankparts/weapon/shot/DiscreteShotModelBase.h \
    game/projects/tanks/client/battlefield/models/tankparts/weapon/shot/ShotCC.h \
    game/projects/tanks/client/battlefield/models/tankparts/weapon/turret/RotatingTurretCC.h \
    game/projects/tanks/client/battlefield/models/tankparts/weapon/turret/RotatingTurretModelBase.h \
    game/projects/tanks/client/battlefield/models/tankparts/weapon/twins/ITwinsModelBase.h \
    game/projects/tanks/client/battlefield/models/tankparts/weapon/twins/TwinsCC.h \
    game/projects/tanks/client/battlefield/models/tankparts/weapon/twins/TwinsModelBase.h \
    game/projects/tanks/client/battlefield/models/tankparts/weapon/weakening/WeaponWeakeningCC.h \
    game/projects/tanks/client/battlefield/models/tankparts/weapon/weakening/WeaponWeakeningModelBase.h \
    game/projects/tanks/client/battlefield/models/user/configuration/TankConfigurationCC.h \
    game/projects/tanks/client/battlefield/models/user/configuration/TankConfigurationModelBase.h \
    game/projects/tanks/client/battlefield/models/user/speedcharacteristics/SpeedCharacteristicsCC.h \
    game/projects/tanks/client/battlefield/models/user/speedcharacteristics/SpeedCharacteristicsModelBase.h \
    game/projects/tanks/client/battlefield/models/user/tank/TankCC.h \
    game/projects/tanks/client/battlefield/models/user/tank/TankLogicState.h \
    game/projects/tanks/client/battlefield/models/user/tank/TankModelBase.h \
    game/projects/tanks/client/battlefield/models/user/tank/commands/TurretControlType.h \
    game/projects/tanks/client/battlefield/models/user/tank/commands/TurretStateCommand.h \
    game/projects/tanks/client/battlefield/types/TankState.h \
    game/projects/tanks/client/battlefield/types/Vector3d.h \
    game/projects/tanks/client/garage/models/item/object3ds/Object3DSCC.h \
    game/projects/tanks/client/garage/models/item/object3ds/Object3DSModelBase.h \
    game/projects/tanks/clients/flash/resources/object3ds/IObject3DS.h \
    game/projects/tanks/clients/flash/resources/object3ds/IObject3DSAdapt.h \
    game/projects/tanks/clients/flash/resources/resource/MapResource.h \
    game/projects/tanks/clients/flash/resources/resource/PropLibResource.h \
    game/projects/tanks/clients/flash/resources/resource/ResourceParams.h \
    game/projects/tanks/clients/flash/resources/resource/Tanks3DSResource.h \
    game/projects/tanks/clients/flash/resources/tanks/Tank3D.h \
    getBattleRunner.h \
    getBindingAction.h \
    getTimer.h \
    global_class.h \
    hardware/alternativa/engine3d/containers/ConflictContainer.h \
    hardware/alternativa/engine3d/containers/KDContainer.h \
    hardware/alternativa/engine3d/containers/KDNode.h \
    hardware/alternativa/engine3d/core/Camera3D.h \
    hardware/alternativa/engine3d/core/Clipping.h \
    hardware/alternativa/engine3d/core/EllipsoidCollider.h \
    hardware/alternativa/engine3d/core/Face.h \
    hardware/alternativa/engine3d/core/MipMapping.h \
    hardware/alternativa/engine3d/core/Object3D.h \
    hardware/alternativa/engine3d/core/Object3DContainer.h \
    hardware/alternativa/engine3d/core/Shadow.h \
    hardware/alternativa/engine3d/core/Sorting.h \
    hardware/alternativa/engine3d/core/VG.h \
    hardware/alternativa/engine3d/core/Vertex.h \
    hardware/alternativa/engine3d/core/View.h \
    hardware/alternativa/engine3d/core/Wrapper.h \
    hardware/alternativa/engine3d/loaders/Parser3DS.h \
    hardware/alternativa/engine3d/materials/FillMaterial.h \
    hardware/alternativa/engine3d/materials/Material.h \
    hardware/alternativa/engine3d/materials/TextureMaterial.h \
    hardware/alternativa/engine3d/materials/TextureResourcesRegistry.h \
    hardware/alternativa/engine3d/materials/UVMatrixProvider.h \
    hardware/alternativa/engine3d/objects/BSP.h \
    hardware/alternativa/engine3d/objects/Decal.h \
    hardware/alternativa/engine3d/objects/Mesh.h \
    hardware/alternativa/engine3d/objects/Occluder.h \
    hardware/alternativa/engine3d/objects/Sprite3D.h \
    hardware/alternativa/gfx/core/BitmapTextureResource.h \
    hardware/alternativa/gfx/core/GfxResource.h \
    hardware/alternativa/gfx/core/GfxTextureResource.h \
    hardware/alternativa/gfx/core/IndexBufferResource.h \
    hardware/alternativa/gfx/core/VertexBufferResource.h \
    hardware/alternativa/tanks/materials/AnimatedPaintMaterial.h \
    hardware/alternativa/tanks/materials/PaintMaterial.h \
    hardware/alternativa/tanks/materials/TrackMaterial.h \
    mainwindow.h \
    path.h \
    qhash_shared_ptr.h \
    qhash_std_string.h \
    shared.h \
    shared_qhash.h \
    stream/s_endian.h \
    stream/stream_read.h \
    view/primitive/WidgetPrimitive.h \
    vulkan/EVulkanWindow.h \
    vulkan/PaintMaterialVulkan.h \
    vulkan/TextureMaterialVulkan.h \
    vulkan/TrackMaterialVulkan.h \
    vulkan/VK_createInstance.h \
    vulkan/VulkanFunctions.h \
    vulkan/VulkanTextureBuffer.h \
    vulkan/VulkanWindow.h \
    view/vulkan/VulkanWindow2.h \
    vulkan/shader.h

SOURCES += \
    Canvas.cpp \
    Debug.cpp \
    Error.cpp \
    FPSService.cpp \
    Graphics.cpp \
    MyList/MyList.cpp \
    MyMath.cpp \
    ResourcesData.cpp \
    _global.cpp \
    _init.cpp \
    entrance/alternativa/types/Long.cpp \
    entrance/platform/client/fp10/core/model/impl/Model.cpp \
    entrance/platform/client/fp10/core/registry/impl/ResourceRegistryImpl.cpp \
    entrance/platform/client/fp10/core/resource/Resource.cpp \
    entrance/platform/client/fp10/core/resource/ResourceInfo.cpp \
    entrance/platform/client/fp10/core/resource/tara/TARAParser.cpp \
    entrance/platform/client/fp10/core/resource/types/MultiframeTextureResource.cpp \
    entrance/platform/client/fp10/core/resource/types/StubBitmapData.cpp \
    entrance/platform/client/fp10/core/resource/types/TextureResource.cpp \
    entrance/platform/client/fp10/core/type/impl/GameObject.cpp \
    entrance/platform/client/fp10/core/type/impl/Space.cpp \
    entrance/projects/tanks/client/battleservice/model/battle/team/BattleTeam.cpp \
    file.cpp \
    flash/display/BitmapData.cpp \
    flash/display3D/VK_IndexBuffer3D.cpp \
    flash/display3D/VK_VertexBuffer3D.cpp \
    flash/geom/ColorTransform.cpp \
    flash/geom/Matrix.cpp \
    flash/geom/Matrix3D.cpp \
    flash/geom/Point.cpp \
    flash/geom/Vector3D.cpp \
    game/alternativa/math/Matrix3.cpp \
    game/alternativa/math/Matrix4.cpp \
    game/alternativa/math/Quaternion.cpp \
    game/alternativa/math/Vector3.cpp \
    game/alternativa/physics/Body.cpp \
    game/alternativa/physics/BodyContact.cpp \
    game/alternativa/physics/BodyState.cpp \
    game/alternativa/physics/PhysicsMaterial.cpp \
    game/alternativa/physics/PhysicsScene.cpp \
    game/alternativa/physics/PhysicsUtils.cpp \
    game/alternativa/physics/QuickUnionFind.cpp \
    game/alternativa/physics/ShapeContact.cpp \
    game/alternativa/physics/collision/CollisionKdNode.cpp \
    game/alternativa/physics/collision/CollisionKdTree.cpp \
    game/alternativa/physics/collision/CollisionKdTree2D.cpp \
    game/alternativa/physics/collision/CollisionShape.cpp \
    game/alternativa/physics/collision/colliders/BoxBoxCollider.cpp \
    game/alternativa/physics/collision/colliders/BoxRectCollider.cpp \
    game/alternativa/physics/collision/colliders/BoxSphereCollider.cpp \
    game/alternativa/physics/collision/colliders/BoxTriangleCollider.cpp \
    game/alternativa/physics/collision/colliders/ColliderUtils.cpp \
    game/alternativa/physics/collision/colliders/PolygonsIntersectionUtils.cpp \
    game/alternativa/physics/collision/primitives/CollisionBox.cpp \
    game/alternativa/physics/collision/primitives/CollisionRect.cpp \
    game/alternativa/physics/collision/primitives/CollisionSphere.cpp \
    game/alternativa/physics/collision/primitives/CollisionTriangle.cpp \
    game/alternativa/physics/collision/types/AABB.cpp \
    game/alternativa/physics/collision/types/RayHit.cpp \
    game/alternativa/physics/contactislands/ContactIsland.cpp \
    game/alternativa/physics/contactislands/ContactLevels.cpp \
    game/alternativa/physics/contactislands/IslandsGenerator.cpp \
    game/alternativa/proplib/PropLibRegistry.cpp \
    game/alternativa/proplib/PropLibrary.cpp \
    game/alternativa/proplib/objects/PropMesh.cpp \
    game/alternativa/proplib/objects/PropSprite.cpp \
    game/alternativa/proplib/types/PropData.cpp \
    game/alternativa/proplib/types/PropGroup.cpp \
    game/alternativa/proplib/types/PropState.cpp \
    game/alternativa/proplib/utils/ByteArrayMap.cpp \
    game/alternativa/proplib/utils/TextureByteDataMap.cpp \
    game/alternativa/tanks/battle/objects/tank/tankskin/TrackSkin.cpp \
    game/alternativa/tanks/battle/objects/tank/tankskin/TracksAnimator.cpp \
    game/alternativa/tanks/battle/objects/tank/tankskin/materialfactory/DefaultTankSkinMaterialsFactory.cpp \
    game/alternativa/tanks/battle/scene3d/DecalFactory.cpp \
    game/alternativa/tanks/battle/scene3d/DeferredRendererAddition.cpp \
    game/alternativa/tanks/battle/scene3d/DeferredRendererDeletion.cpp \
    game/alternativa/tanks/battle/scene3d/RenderGroup.cpp \
    game/alternativa/tanks/battle/scene3d/RotationState.cpp \
    game/alternativa/tanks/battle/utils/AddPostPhysicsControllerAction.cpp \
    game/alternativa/tanks/battle/utils/PhysicsControllerDeferredAction.cpp \
    game/alternativa/tanks/battle/utils/RemovePostPhysicsController.cpp \
    game/alternativa/tanks/engine3d/AnimatedSprite3D.cpp \
    game/alternativa/tanks/engine3d/CachedEntityStat.cpp \
    game/alternativa/tanks/engine3d/DefaultEffectsMaterialRegistry.cpp \
    game/alternativa/tanks/engine3d/DefaultTextureMaterialFactory.cpp \
    game/alternativa/tanks/engine3d/MaterialEntry.cpp \
    game/alternativa/tanks/engine3d/MutableTextureMaterialRegistry.cpp \
    game/alternativa/tanks/engine3d/TextureMaterialRegistryBase.cpp \
    game/alternativa/tanks/model/item3d/Object3DSModel.cpp \
    game/alternativa/tanks/models/battle/battlefield/map/Billboards.cpp \
    game/alternativa/tanks/models/battle/battlefield/map/NormalsCalculator.cpp \
    game/alternativa/tanks/models/battle/battlefield/map/TexturedSpritesCollection.cpp \
    game/alternativa/tanks/models/tank/ITankModelAdapt.cpp \
    game/alternativa/tanks/models/tank/InitTankPartAdapt.cpp \
    game/alternativa/tanks/models/tank/WeaponMountProviderAdapt.cpp \
    game/alternativa/tanks/models/tank/configuration/TankConfigurationAdapt.cpp \
    game/alternativa/tanks/models/tank/configuration/TankConfigurationModel.cpp \
    game/alternativa/tanks/models/tank/hullcommon/HullCommonAdapt.cpp \
    game/alternativa/tanks/models/tank/hullcommon/HullCommonModel.cpp \
    game/alternativa/tanks/models/tank/speedcharacteristics/SpeedCharacteristicsAdapt.cpp \
    game/alternativa/tanks/models/weapon/IWeaponModelAdapt.cpp \
    game/alternativa/tanks/models/weapon/angles/verticals/autoaiming/VerticalAutoAimingAdapt.cpp \
    game/alternativa/tanks/models/weapon/angles/verticals/verticalangles/VerticalAnglesAdapt.cpp \
    game/alternativa/tanks/models/weapon/angles/verticals/verticalangles/WeaponVerticalAnglesModel.cpp \
    game/alternativa/tanks/models/weapon/angles/verticals/autoaiming/VerticalAutoAimingModel.cpp \
    game/alternativa/tanks/models/weapon/common/WeaponCommonModel.cpp \
    game/alternativa/tanks/models/weapon/common/asWeaponCommon.cpp \
    game/alternativa/tanks/models/weapon/shared/shot/DiscreteShotModel.cpp \
    game/alternativa/tanks/models/weapon/shared/shot/IShotModelAdapt.cpp \
    game/alternativa/tanks/models/weapon/turret/IRotatingTurretModelAdapt.cpp \
    game/alternativa/tanks/models/weapon/twins/ITwinsSFXModelAdapt.cpp \
    game/alternativa/tanks/models/weapon/twins/RemoteTwinsWeapon.cpp \
    game/alternativa/tanks/models/weapon/twins/TwinsAmmunition.cpp \
    game/alternativa/tanks/models/weapon/twins/TwinsEffects.cpp \
    game/alternativa/tanks/models/weapon/twins/TwinsModel.cpp \
    game/alternativa/tanks/models/weapon/twins/TwinsSFXModel.cpp \
    game/alternativa/tanks/models/weapon/twins/TwinsShot.cpp \
    game/alternativa/tanks/models/weapon/twins/TwinsShotParams.cpp \
    game/alternativa/tanks/models/weapon/twins/TwinsWeapon.cpp \
    game/alternativa/tanks/models/weapon/twins/TwinsWeaponCallbackAdapt.cpp \
    game/alternativa/tanks/models/weapon/weakening/IWeaponWeakeningModelAdapt.cpp \
    game/alternativa/tanks/models/weapon/weakening/WeaponWeakeningModel.cpp \
    game/alternativa/tanks/models/weapons/shell/InelasticShell.cpp \
    game/alternativa/tanks/models/weapons/shell/Shell.cpp \
    game/alternativa/tanks/models/weapons/shell/states/DummyShellStates.cpp \
    game/alternativa/tanks/models/weapons/shell/states/ShellStates.cpp \
    game/alternativa/tanks/sfx/AnimatedSpriteEffect.cpp \
    game/alternativa/tanks/sfx/DecalEffect.cpp \
    game/alternativa/tanks/sfx/PlaneMuzzleFlashEffect.cpp \
    game/alternativa/tanks/sfx/SFXUtils.cpp \
    game/alternativa/tanks/sfx/SimplePlane.cpp \
    game/alternativa/tanks/sfx/StaticObject3DPositionProvider.cpp \
    game/alternativa/tanks/sfx/christmas/ChristmasTreeToyEffect.cpp \
    game/alternativa/tanks/battle/BattleRunner.cpp \
    game/alternativa/tanks/battle/BattleUtils.cpp \
    game/alternativa/tanks/battle/BattleView.cpp \
    game/alternativa/tanks/battle/PerformanceMonitor.cpp \
    game/alternativa/tanks/battle/objects/tank/CollisionBoxesBuilder.cpp \
    game/alternativa/tanks/battle/objects/tank/EncryptedValueSmoother.cpp \
    game/alternativa/tanks/battle/objects/tank/HullNotFoundError.cpp \
    game/alternativa/tanks/battle/objects/tank/LocalHullTransformUpdater.cpp \
    game/alternativa/tanks/battle/objects/tank/RemoteHullTransformUpdater.cpp \
    game/alternativa/tanks/battle/objects/tank/SimpleValueSmoother.cpp \
    game/alternativa/tanks/battle/objects/tank/Tank.cpp \
    game/alternativa/tanks/battle/objects/tank/TankConst.cpp \
    game/alternativa/tanks/battle/objects/tank/TankControlLockBits.cpp \
    game/alternativa/tanks/battle/objects/tank/TurretMountPointNotFoundError.cpp \
    game/alternativa/tanks/battle/objects/tank/controllers/BarrelElevator.cpp \
    game/alternativa/tanks/battle/objects/tank/controllers/ChassisController.cpp \
    game/alternativa/tanks/battle/objects/tank/controllers/LocalChassisController.cpp \
    game/alternativa/tanks/battle/objects/tank/controllers/LocalTurretController.cpp \
    game/alternativa/tanks/battle/objects/tank/controllers/Turret.cpp \
    game/alternativa/tanks/battle/objects/tank/tankchassis/SuspensionParams.cpp \
    game/alternativa/tanks/battle/objects/tank/tankchassis/SuspensionRay.cpp \
    game/alternativa/tanks/battle/objects/tank/tankchassis/Track.cpp \
    game/alternativa/tanks/battle/objects/tank/tankchassis/TrackedChassis.cpp \
    game/alternativa/tanks/battle/objects/tank/tankskin/TankHullSkinCacheItem.cpp \
    game/alternativa/tanks/battle/objects/tank/tankskin/TankSkin.cpp \
    game/alternativa/tanks/battle/objects/tank/tankskin/TankSkinPartCacheItem.cpp \
    game/alternativa/tanks/battle/objects/tank/tankskin/turret/TurretGeometryItem.cpp \
    game/alternativa/tanks/battle/objects/tank/tankskin/turret/TurretSkin.cpp \
    game/alternativa/tanks/battle/objects/tank/tankskin/turret/TurretSkinCacheItem.cpp \
    game/alternativa/tanks/battle/scene3d/AmbientShadows.cpp \
    game/alternativa/tanks/battle/scene3d/BattleScene3D.cpp \
    game/alternativa/tanks/battle/scene3d/Object3DNames.cpp \
    game/alternativa/tanks/battle/scene3d/scene3dcontainer/Object3DContainerProxy.cpp \
    game/alternativa/tanks/battle/utils/DampedSpring.cpp \
    game/alternativa/tanks/camera/DummyCameraController.cpp \
    game/alternativa/tanks/camera/FollowCameraController.cpp \
    game/alternativa/tanks/camera/GameCamera.cpp \
    game/alternativa/tanks/display/AxisIndicator.cpp \
    game/alternativa/tanks/engine3d/IndexedTextureConstructor.cpp \
    game/alternativa/tanks/models/battle/battlefield/BattlefieldModel.cpp \
    game/alternativa/tanks/models/battle/battlefield/CommonTargetEvaluatorConst.cpp \
    game/alternativa/tanks/models/battle/battlefield/map/CollisionGeometryParser.cpp \
    game/alternativa/tanks/models/battle/battlefield/map/CollisionGeometryToXml.cpp \
    game/alternativa/tanks/models/battle/battlefield/map/HelperMesh.cpp \
    game/alternativa/tanks/models/battle/battlefield/map/MapBuilder.cpp \
    game/alternativa/tanks/models/battle/battlefield/map/MapGeometryParser.cpp \
    game/alternativa/tanks/models/battle/battlefield/map/MapTexturesBuilder.cpp \
    game/alternativa/tanks/models/battle/battlefield/map/TexturedBSPsCollection.cpp \
    game/alternativa/tanks/models/battle/battlefield/map/TexturedMeshesCollection.cpp \
    game/alternativa/tanks/models/battle/battlefield/map/TexturedPropsRegistry.cpp \
    game/alternativa/tanks/models/map/BattleMapModel.cpp \
    game/alternativa/tanks/models/tank/HullsRegistry.cpp \
    game/alternativa/tanks/models/tank/LocalWeaponController.cpp \
    game/alternativa/tanks/models/tank/RemoteWeaponController.cpp \
    game/alternativa/tanks/models/tank/TankModel.cpp \
    game/alternativa/tanks/models/tank/TankPartsRegistry.cpp \
    game/alternativa/tanks/models/tank/TurretsRegistry.cpp \
    game/alternativa/tanks/models/tank/speedcharacteristics/SpeedCharacteristicsModel.cpp \
    game/alternativa/tanks/models/weapon/RayCollisionFilter.cpp \
    game/alternativa/tanks/models/weapon/WeaponConst.cpp \
    game/alternativa/tanks/models/weapon/WeaponForces.cpp \
    game/alternativa/tanks/models/weapon/WeaponObject.cpp \
    game/alternativa/tanks/models/weapon/WeaponUtils.cpp \
    game/alternativa/tanks/models/weapon/artillery/rotation/ArtilleryElevatingBarrelModel.cpp \
    game/alternativa/tanks/models/weapon/artillery/rotation/BarrelElevationController.cpp \
    game/alternativa/tanks/models/weapon/common/HitInfo.cpp \
    game/alternativa/tanks/models/weapon/common/IWeaponCommonModelAdapt.cpp \
    game/alternativa/tanks/models/weapon/common/WeaponCommonData.cpp \
    game/alternativa/tanks/models/weapon/shared/MarginalCollider.cpp \
    game/alternativa/tanks/models/weapon/shared/SimpleWeaponController.cpp \
    game/alternativa/tanks/models/weapon/smoky/RemoteSmokyWeapon.cpp \
    game/alternativa/tanks/models/weapon/smoky/SmokyWeapon.cpp \
    game/alternativa/tanks/models/weapon/turret/RotatingTurretModel.cpp \
    game/alternativa/tanks/models/weapon/weakening/DistanceWeakening.cpp \
    game/alternativa/tanks/models/weapons/targeting/CommonTargetingSystem.cpp \
    game/alternativa/tanks/models/weapons/targeting/TargetingResult.cpp \
    game/alternativa/tanks/models/weapons/targeting/TargetingSystem.cpp \
    game/alternativa/tanks/models/weapons/targeting/direction/TargetingDirection.cpp \
    game/alternativa/tanks/models/weapons/targeting/direction/sector/SectorDirectionCalculator.cpp \
    game/alternativa/tanks/models/weapons/targeting/direction/sector/TargetingSector.cpp \
    game/alternativa/tanks/models/weapons/targeting/direction/sector/TargetingSectorList.cpp \
    game/alternativa/tanks/models/weapons/targeting/direction/sector/TargetingSectorsCalculator.cpp \
    game/alternativa/tanks/models/weapons/targeting/direction/sector/splitter/SectorsSplitter.cpp \
    game/alternativa/tanks/models/weapons/targeting/direction/sector/splitter/SortedTargetingSectors.cpp \
    game/alternativa/tanks/models/weapons/targeting/priority/TargetingPriorityCalculator.cpp \
    game/alternativa/tanks/models/weapons/targeting/priority/targeting/CommonTargetPriorityCalculator.cpp \
    game/alternativa/tanks/models/weapons/targeting/processor/CommonDirectionProcessor.cpp \
    game/alternativa/tanks/models/weapons/targeting/processor/SingleTargetDirectionProcessor.cpp \
    game/alternativa/tanks/physics/SoaringChecker.cpp \
    game/alternativa/tanks/physics/TankBody.cpp \
    game/alternativa/tanks/physics/TankBodyIdProvider.cpp \
    game/alternativa/tanks/physics/TankPhysicsScene.cpp \
    game/alternativa/tanks/physics/TanksCollisionDetector.cpp \
    game/alternativa/tanks/services/battleinput/BattleInputServiceImpl.cpp \
    game/alternativa/tanks/services/tankregistry/TankUsersRegistryServiceImpl.cpp \
    game/alternativa/tanks/utils/BitMask.cpp \
    game/alternativa/tanks/utils/BitVector.cpp \
    game/alternativa/tanks/utils/ConstEncryptedNumber.cpp \
    game/alternativa/tanks/utils/EncryptedIntImpl.cpp \
    game/alternativa/tanks/utils/EncryptedNumberImpl.cpp \
    game/alternativa/tanks/utils/GraphicsUtils.cpp \
    game/alternativa/tanks/utils/MathUtils.cpp \
    game/alternativa/tanks/utils/Vector3Validator.cpp \
    game/alternativa/tanks/utils/objectpool/ObjectPool.cpp \
    game/alternativa/tanks/utils/objectpool/Pool.cpp \
    game/alternativa/tanks/utils/objectpool/PooledObject.cpp \
    game/alternativa/utils/XMLUtils.cpp \
    game/alternativa/utils/textureutils/TextureConstructor.cpp \
    game/projects/tanks/client/battlefield/models/tankparts/armor/common/HullCommonModelBase.cpp \
    game/projects/tanks/client/battlefield/models/tankparts/sfx/shoot/twins/TwinsShootSFXModelBase.cpp \
    game/projects/tanks/client/battlefield/models/tankparts/weapon/angles/verticals/autoaiming/VerticalAutoAimingModelBase.cpp \
    game/projects/tanks/client/battlefield/models/tankparts/weapon/angles/verticals/verticalangles/WeaponVerticalAnglesModelBase.cpp \
    game/projects/tanks/client/battlefield/models/tankparts/weapon/common/WeaponCommonModelBase.cpp \
    game/projects/tanks/client/battlefield/models/tankparts/weapon/common/shell/ShellState.cpp \
    game/projects/tanks/client/battlefield/models/tankparts/weapon/shot/DiscreteShotModelBase.cpp \
    game/projects/tanks/client/battlefield/models/tankparts/weapon/turret/RotatingTurretModelBase.cpp \
    game/projects/tanks/client/battlefield/models/tankparts/weapon/twins/TwinsModelBase.cpp \
    game/projects/tanks/client/battlefield/models/tankparts/weapon/weakening/WeaponWeakeningModelBase.cpp \
    game/projects/tanks/client/battlefield/models/user/configuration/TankConfigurationModelBase.cpp \
    game/projects/tanks/client/battlefield/models/user/speedcharacteristics/SpeedCharacteristicsModelBase.cpp \
    game/projects/tanks/client/battlefield/models/user/tank/TankLogicState.cpp \
    game/projects/tanks/client/battlefield/models/user/tank/TankModelBase.cpp \
    game/projects/tanks/client/battlefield/models/user/tank/commands/TurretStateCommand.cpp \
    game/projects/tanks/client/battlefield/types/TankState.cpp \
    game/projects/tanks/client/garage/models/item/object3ds/Object3DSModelBase.cpp \
    game/projects/tanks/clients/flash/resources/object3ds/IObject3DSAdapt.cpp \
    game/projects/tanks/clients/flash/resources/resource/MapResource.cpp \
    game/projects/tanks/clients/flash/resources/resource/PropLibResource.cpp \
    game/projects/tanks/clients/flash/resources/resource/ResourceParams.cpp \
    game/projects/tanks/clients/flash/resources/resource/Tanks3DSResource.cpp \
    game/projects/tanks/clients/flash/resources/tanks/Tank3D.cpp \
    getBattleRunner.cpp \
    getBindingAction.cpp \
    getTimer.cpp \
    global_class.cpp \
    hardware/alternativa/engine3d/containers/ConflictContainer.cpp \
    hardware/alternativa/engine3d/containers/KDContainer.cpp \
    hardware/alternativa/engine3d/containers/KDNode.cpp \
    hardware/alternativa/engine3d/core/Camera3D.cpp \
    hardware/alternativa/engine3d/core/Clipping.cpp \
    hardware/alternativa/engine3d/core/EllipsoidCollider.cpp \
    hardware/alternativa/engine3d/core/Face.cpp \
    hardware/alternativa/engine3d/core/Object3D.cpp \
    hardware/alternativa/engine3d/core/Object3DContainer.cpp \
    hardware/alternativa/engine3d/core/Shadow.cpp \
    hardware/alternativa/engine3d/core/Sorting.cpp \
    hardware/alternativa/engine3d/core/VG.cpp \
    hardware/alternativa/engine3d/core/Vertex.cpp \
    hardware/alternativa/engine3d/core/View.cpp \
    hardware/alternativa/engine3d/core/Wrapper.cpp \
    hardware/alternativa/engine3d/loaders/Parser3DS.cpp \
    hardware/alternativa/engine3d/materials/FillMaterial.cpp \
    hardware/alternativa/engine3d/materials/Material.cpp \
    hardware/alternativa/engine3d/materials/TextureMaterial.cpp \
    hardware/alternativa/engine3d/materials/TextureResourcesRegistry.cpp \
    hardware/alternativa/engine3d/materials/UVMatrixProvider.cpp \
    hardware/alternativa/engine3d/objects/BSP.cpp \
    hardware/alternativa/engine3d/objects/Decal.cpp \
    hardware/alternativa/engine3d/objects/Mesh.cpp \
    hardware/alternativa/engine3d/objects/Occluder.cpp \
    hardware/alternativa/engine3d/objects/Sprite3D.cpp \
    hardware/alternativa/gfx/core/BitmapTextureResource.cpp \
    hardware/alternativa/gfx/core/GfxResource.cpp \
    hardware/alternativa/gfx/core/GfxTextureResource.cpp \
    hardware/alternativa/gfx/core/IndexBufferResource.cpp \
    hardware/alternativa/gfx/core/VertexBufferResource.cpp \
    hardware/alternativa/tanks/materials/AnimatedPaintMaterial.cpp \
    hardware/alternativa/tanks/materials/PaintMaterial.cpp \
    hardware/alternativa/tanks/materials/TrackMaterial.cpp \
    main.cpp \
    mainwindow.cpp \
    path.cpp \
    stream/stream_read.cpp \
    view/primitive/WidgetPrimitive.cpp \
    vulkan/EVulkanWindow.cpp \
    vulkan/PaintMaterialVulkan.cpp \
    vulkan/TextureMaterialVulkan.cpp \
    vulkan/TrackMaterialVulkan.cpp \
    vulkan/VK_createInstance.cpp \
    vulkan/VulkanFunctions.cpp \
    vulkan/VulkanTextureBuffer.cpp \
    view/vulkan/VulkanWindow2.cpp \
    vulkan/shader.cpp

