#ifndef GAMEACTIONENUM_H
#define GAMEACTIONENUM_H

enum class GameActionEnum
{
	_NULL,
	ROTATE_TURRET_LEFT,
	ROTATE_TURRET_RIGHT,
	CENTER_TURRET,
	CHASSIS_LEFT_MOVEMENT,
	CHASSIS_RIGHT_MOVEMENT,
	CHASSIS_FORWARD_MOVEMENT,
	CHASSIS_BACKWARD_MOVEMENT,
	FOLLOW_CAMERA_UP,
	FOLLOW_CAMERA_DOWN,
	DROP_FLAG,
	BATTLE_PAUSE,
	BATTLE_VIEW_INCREASE,
	BATTLE_VIEW_DECREASE,
	FULL_SCREEN,
	SUICIDE,
	SHOW_TANK_PARAMETERS,
	USE_FIRS_AID,
	USE_DOUBLE_ARMOR,
	USE_DOUBLE_DAMAGE,
	USE_NITRO,
	USE_MINE,
	DROP_GOLD_BOX,
	SHOT,
	ULTIMATE,
	OPEN_GARAGE,
	SHOW_BATTLE_STATS_TABLE,
	LOOK_AROUND
};

#endif // GAMEACTIONENUM_H
